language: java
sudo: false
cache: bundler
jdk: oraclejdk8

before_install:
- git clone https://github.com/graalvm/mx --depth 1
- export PATH=$PWD/mx:$PATH
- git clone https://github.com/graalvm/truffleruby
- cd truffleruby
- echo MX_BINARY_SUITES=truffle >> mx.jruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.jruby/env
- mx build
- "> ~/.rvm/gemsets/global.gems"
- "> ~/.rvm/gemsets/default.gems"
- rvm mount $PWD -n truffleruby
- rvm use ext-truffleruby
- export RUBYOPT=-ropenssl-stubs
- gem uninstall bundler -a -x
- gem install bundler -v 1.13.7
- bundle install

install: "echo $PWD"
script: ruby -Ilib exe/rake
